### PR TITLE
Adds note about sharing responsibility.

### PR DESCRIPTION
**Pull request by ashfurrow**
Getting _every_ engineer at Artsy to run at least one standup has been a goal of mine for months now; this PR elevates that goal from being a personal one to being a goal of the whole team. Let's make sure to give some time for discussion on this one, to make sure everyone is aware of the change and has an opportunity to voice any feedback.

### CODE REVIEW

**Comment by acjay** [comment]
This is an interesting concept. My first reaction was that I'm wary of mandates for everyone to participate in something, just because different people have different strengths, weaknesses, and inclinations. My perhaps irrational fear is that if more mandatory things appear, then will it start to feel like a chore schedule.

That said, I haven't run a standup yet but it seems to be pretty painless to do, thanks to the work you've put in. It probably _would_ be a good thing if everyone did take a turn. And I like the concept of innovating-then-socializing as a way of building out our team practices, without overreliance on any small group of people.

So, mixed feelings, but down for whatevs!

**Comment by ashfurrow** [comment]
I hear what you're saying, and I share your concern about foisting responsibilities on others. What was unsaid in the PR description is that: by getting everyone to participate, we also get feedback from everyone on how the process works for them. This lets us structure a standup process that is increasingly inclusive of folks with different strengths. We already, for example, have both a talking role and a note-taking role, so if someone isn't too keen on speaking in front of a large group, they're still able to participate in running the standup. I hope that sheds light on my motivation, let me know what else I can clarify.

**Comment by cavvia** [comment]
I'm generally in favour of this, but I'm also in favour of every engineer having a say over the structure of our team standup as well.

A key question for me with our standup is - who is it serving? The new sprint status updates only appear to serve product management, not other engineers... because there is no time to include any technical details. I don't gain much from them as an engineer.

**Comment by ashfurrow** [comment]
@cavvia That's a really great point. We shortened the team updates because we got feedback that they were too detailed, and to make up for that lost knowledge-sharing, we've been trying things like [Show & Tell](https://github.com/artsy/meta/blob/master/meta/show_and_tell.md). But that's not a replacement for the technical details we used to discuss in our standups. Would you be interested in opening up an issue on this repo to discuss the detail that would be appropriate in standup team updates?

**Comment by cavvia** [comment]
The issue is that there are too many teams reporting in because we are running too many parallel sprints... so I don't think altering the team updates can fix the problem. It's a more structural issue.

**Comment by orta** [comment]
WRT the standup format - it's *always* up for discussion ( we have a slack channel for this #open-standup ) - I think the wording here is light enough to say that it's not mandatory for everyone to do it, but it's an ideal. I'm 👍 for this change.

**Comment by jonallured** [comment]
My two cents: as a remoter, I was a little worried about running my first standup this week, but the work that's been done to document the process made it really easy!! I like the idea of positioning this meeting as something anyone can run. The fact that there's two roles (speaking, note taking) is nice too because I think it acknowledges that different people have different strengths.

Unless anyone else feels strongly about this one, I'm going to leave it open until Monday and then merge. Thanks for the discussion!!

**Pull request merged**
